name: paddle-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - botocore
  - curl
  - git
  - numpy<1.24
  - pip
  - psutil
  - python=3.8.10
  - tqdm
  - backports.zoneinfo
  # S3MP
  - aioboto3
  - boto3-stubs
  - future
  - mypy-boto3-s3
  - pyparsing
  - pyproj
  - setuptools
