python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row1a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row1b/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row2a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row2b/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row3a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row3b/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row4a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row4b/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row5a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row5b/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row6a/measurements_df.gz --threshold
python scripts/analyze_data.py -d s3_mirror/FC22_StripTrial_P1_6-21_Row6b/measurements_df.gz --threshold