python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row1_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row2_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row2_staked_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row3_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row3_staked_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row4_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_6-27_Row5_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row1_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row2_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row2_staked_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row3_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row3_staked_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row4_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/PF1_7-05_Row5_s3_keys.json
