python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row01_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row02_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row03_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row04_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row05_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row06_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row07_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row08_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row09_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row10_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row11_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row12_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row13_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row14_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row15_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FF2_7-08_Row16_s3_keys.json