python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row1b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row2b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row3b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row4b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row5b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row6b_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row1a_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row2a_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row3a_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row4a_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row5a_s3_keys.json
python scripts/pull_inferenced_data.py -i jsons/FC22_StripTrial_P1_6-21_Row6a_s3_keys.json