# tmux new-session -d -s "Week1,Row1" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row1/ --threshold 800"
# tmux new-session -d -s "Week1,Row2" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row2/ --threshold 800"
# tmux new-session -d -s "Week1,Row2_staked" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row2_staked/ --threshold 800"
# tmux new-session -d -s "Week1,Row3" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row3/ --threshold 850"
# tmux new-session -d -s "Week1,Row3_staked" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row3_staked/ --threshold 850"
# tmux new-session -d -s "Week1,Row4" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row4/ --threshold 750"
# tmux new-session -d -s "Week1,Row5" "python scripts/run_analysis.py --dir s3_mirror/PF1_6-27_Row5/ --threshold 800"
tmux new-session -d -s "Week2,Row1" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row1/ --threshold 800"
tmux new-session -d -s "Week2,Row2" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row2/ --threshold 850"
tmux new-session -d -s "Week2,Row2staked" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row2_staked/ --threshold 800"
tmux new-session -d -s "Week2,Row3" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row3/ --threshold 900"
tmux new-session -d -s "Week2,Row3staked" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row3_staked/ --threshold 900"
tmux new-session -d -s "Week2,Row4" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row4/ --threshold 700"
# tmux new-session -d -s "Week2,Row5" "python scripts/run_analysis.py --dir s3_mirror/PF1_7-05_Row5/ --threshold 900"
